// Date: 6/30/2014 6:11:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package tk.yteditors.requiredstuffz.renderer;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class TileEntityOvenRenderer extends ModelBase {
	// fields
	ModelRenderer	Base;
	ModelRenderer	Side1;
	ModelRenderer	Side2;
	ModelRenderer	Top;
	ModelRenderer	Chimney1;
	ModelRenderer	Chimney2;
	ModelRenderer	Chimney3;
	ModelRenderer	Chimney4;
	ModelRenderer	Back;
	
	public TileEntityOvenRenderer() {
		textureWidth = 64;
		textureHeight = 64;
		
		Base = new ModelRenderer(this, 0, 0);
		Base.addBox(0F, 0F, 0F, 7, 1, 7);
		Base.setRotationPoint(-3F, 0F, -3F);
		Base.setTextureSize(64, 32);
		Base.mirror = true;
		setRotation(Base, 0F, 0F, 0F);
		Side1 = new ModelRenderer(this, 0, 0);
		Side1.addBox(0F, 0F, 0F, 1, 3, 7);
		Side1.setRotationPoint(-3F, -3F, -3F);
		Side1.setTextureSize(64, 32);
		Side1.mirror = true;
		setRotation(Side1, 0F, 0F, 0F);
		Side2 = new ModelRenderer(this, 0, 0);
		Side2.addBox(0F, 0F, 0F, 1, 3, 7);
		Side2.setRotationPoint(3F, -3F, -3F);
		Side2.setTextureSize(64, 32);
		Side2.mirror = true;
		setRotation(Side2, 0F, 0F, 0F);
		Top = new ModelRenderer(this, 0, 0);
		Top.addBox(0F, 0F, 0F, 5, 1, 7);
		Top.setRotationPoint(-2F, -4F, -3F);
		Top.setTextureSize(64, 32);
		Top.mirror = true;
		setRotation(Top, 0F, 0F, 0F);
		Chimney1 = new ModelRenderer(this, 0, 0);
		Chimney1.addBox(0F, 0F, 0F, 1, 3, 2);
		Chimney1.setRotationPoint(-1F, -7F, -1F);
		Chimney1.setTextureSize(64, 64);
		Chimney1.mirror = true;
		setRotation(Chimney1, 0F, 0F, 0F);
		Chimney2 = new ModelRenderer(this, 0, 0);
		Chimney2.addBox(0F, 0F, 0F, 2, 3, 1);
		Chimney2.setRotationPoint(-1F, -7F, 1F);
		Chimney2.setTextureSize(64, 64);
		Chimney2.mirror = true;
		setRotation(Chimney2, 0F, 0F, 0F);
		Chimney3 = new ModelRenderer(this, 0, 0);
		Chimney3.addBox(0F, 0F, 0F, 1, 3, 2);
		Chimney3.setRotationPoint(1F, -7F, 0F);
		Chimney3.setTextureSize(64, 64);
		Chimney3.mirror = true;
		setRotation(Chimney3, 0F, 0F, 0F);
		Chimney4 = new ModelRenderer(this, 0, 0);
		Chimney4.addBox(0F, 0F, 0F, 2, 3, 1);
		Chimney4.setRotationPoint(0F, -7F, -1F);
		Chimney4.setTextureSize(64, 64);
		Chimney4.mirror = true;
		setRotation(Chimney4, 0F, 0F, 0F);
		Back = new ModelRenderer(this, 0, 0);
		Back.addBox(0F, 0F, 0F, 5, 3, 1);
		Back.setRotationPoint(-2F, -3F, 3F);
		Back.setTextureSize(64, 64);
		Back.mirror = true;
		setRotation(Back, 0F, 0F, 0F);
	}
	
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		Base.render(f5);
		Side1.render(f5);
		Side2.render(f5);
		Top.render(f5);
		Chimney1.render(f5);
		Chimney2.render(f5);
		Chimney3.render(f5);
		Chimney4.render(f5);
		Back.render(f5);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity) {
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}
	
}
